on:
  push:
  pull_request:

name: x

jobs:
  lint:
    runs-on: windows-latest
    steps:
    - run: tree "C:\Program Files\LLVM"
    - run: Remove-Item -Recurse "C:\Program Files\LLVM"
    - uses: KyleMayes/install-llvm-action@v1
      with:
        version: 13
    - run: tree "C:\Program Files\LLVM"
