on:
  push:
  pull_request:

name: x

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: ls /usr/bin/llvm*
    - name: Make llvm-readobj-12 available
      run: sudo ln -s llvm-readobj-12 /usr/bin/llvm-readobj
    - run: |
        which llvm-readelf || true
        which llvm-readelf-12 || true
        which llvm-readobj || true
        which llvm-readobj-12 || true
  macos:
    runs-on: macos-latest
    steps:
    - run: ls /usr/bin/llvm*
    - name: Make llvm-readobj-12 available
      run: sudo ln -s llvm-readobj-12 /usr/bin/llvm-readobj
    - run: |
        which llvm-readelf || true
        which llvm-readelf-12 || true
        which llvm-readobj || true
        which llvm-readobj-12 || true
    - run: which lld || true
    - run: which clang || true
    - run: ls /usr/local/bin/llvm* || true
